"""Add password sections

Revision ID: 14791a613725
Revises: fbb3e31eacc8
Create Date: 2017-09-05 09:11:53.911189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14791a613725'
down_revision = 'fbb3e31eacc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
